{% set name = "empanada-napari" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/empanada-napari-{{ version }}.tar.gz
  sha256: b2234fc17127cfda16df2afdae121d1f65ed8457e751e54681307a5c93a121c1

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools-scm
  run:
    - empanada-dl >=0.1.4
    - imagecodecs
    - napari >=0.4.13
    - napari-plugin-engine >=0.1.4
    - python >=3.7
    - scikit-image >=0.18

test:
  imports:
    - empanada_napari
  commands:
    - pip list
    # - pip check  # Fails due to opencv-python-headless
  requires:
    - pip

about:
  home: https://github.com/volume-em/empanada-napari
  summary: Napari plugin of algorithms for Panoptic Segmentation of organelles in EM
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
