{% set name = "empanada-napari" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/empanada-napari-{{ version }}.tar.gz
  sha256: f4890cb6f20689933e28903dd7d43238aeae32afb53fa225bdf41d4bdcfc2c71

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools-scm
  run:
    - empanada-dl >=0.1.7
    - imagecodecs
    - napari >=0.4.16
    - napari-plugin-engine >=0.1.4
    - python >=3.7
    - scikit-image >=0.19
    - numpy <1.23.0a0

test:
  imports:
    - empanada_napari
  commands:
    - pip list
    - pip check || true # Fails due to opencv-python-headless
  requires:
    - pip

about:
  home: https://github.com/volume-em/empanada-napari
  summary: Napari plugin of algorithms for Panoptic Segmentation of organelles in EM
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
