{% set name = "empanada-napari" %}
{% set version = "1.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: fdd5f25d231734d6f4db080e7ea9199a9854875e6c3b5a6e0dacfa509f57c5eb

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools-scm
  run:
    - empanada-dl >=0.1.7
    - imagecodecs
    - napari >=0.4.16
    - napari-plugin-engine >=0.1.4
    - python >=3.7
    - scikit-image >=0.19
    - numpy <1.23.0a0

test:
  imports:
    - empanada_napari
  commands:
    - pip list
    - pip check || true # Fails due to opencv-python-headless
  requires:
    - pip

about:
  home: https://github.com/volume-em/empanada-napari
  summary: Napari plugin of algorithms for Panoptic Segmentation of organelles in EM
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
